export function Logo() {
  return (
    <svg
      width="20"
      height="20"
      viewBox="0 0 20 20"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <line
        x1="4"
        y1="16"
        x2="10"
        y2="4"
        stroke="var(--color-edge)"
        strokeWidth="1.5"
      />
      <line
        x1="10"
        y1="4"
        x2="16"
        y2="16"
        stroke="var(--color-edge)"
        strokeWidth="1.5"
      />
      <line
        x1="4"
        y1="16"
        x2="16"
        y2="16"
        stroke="var(--color-edge)"
        strokeWidth="1.5"
      />
      <circle
        cx="10"
        cy="4"
        r="2.5"
        fill="var(--color-canvas)"
        stroke="var(--color-accent)"
        strokeWidth="1.5"
      />
      <circle
        cx="4"
        cy="16"
        r="2.5"
        fill="var(--color-canvas)"
        stroke="var(--color-accent)"
        strokeWidth="1.5"
      />
      <circle
        cx="16"
        cy="16"
        r="2.5"
        fill="var(--color-canvas)"
        stroke="var(--color-accent)"
        strokeWidth="1.5"
      />
    </svg>
  );
}
